=== danielmhdev/EV2---Lenguaje-de-Marcas-XML-DTD-XSD/Ejercicio 2/plataforma.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- Estructura Plataforma + refs-->
    <xs:element name="plataforma">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="cursos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="curso" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="alumnos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="alumno" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="matriculas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="matricula" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="evaluaciones">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="evaluacion" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
         <!-- Atributos Plataforma-->
            <xs:attribute name="fecha_publicacion" type="xs:date" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Estructura Curso-->
     <xs:element name="curso">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"/>
                <xs:element name="nivel" type="nivelCurso"/>
                <xs:element name="modalidad" type="modalidadTipo"/>
                <xs:element name="horas" type="xs:positiveInteger"/>
                <xs:element ref="modulos" minOccurs="0"/>
            </xs:sequence>
                <!-- Atributos Curso-->
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="codigo" type="xs:string" use="optional"/>
        </xs:complexType>
     </xs:element>

     <xs:element name="modulos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="modulo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="horas" type="xs:positiveInteger"/>
                        </xs:sequence>
                    <!-- Atributos Modulo-->
                        <xs:attribute name="clave" type="xs:string" use="optional"/>   
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
     </xs:element>
     
    <!-- Restricciones Curso-->
     <xs:simpleType name="nivelCurso">
        <xs:restriction base="xs:string">
            <xs:pattern value="Basico|Medio|Avanzado"/>
        </xs:restriction>
    </xs:simpleType>

     <xs:simpleType name="modalidadTipo">
        <xs:restriction base="xs:string">
            <xs:pattern value="Online|Presencial"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Estructura Alumnos-->
     <xs:element name="alumno">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="email" type="emailTipo"/>
                <xs:element name="telefono" type="telefonoTipo" minOccurs="0"/>
            </xs:sequence>
             <!-- Atributos Alumno-->
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="nif" type="nifTipo" use="optional"/>
        </xs:complexType> 
     </xs:element>

    <!-- Restricciones Alumno-->
     <xs:simpleType name="emailTipo">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}"/>
        </xs:restriction>
     </xs:simpleType>

     <xs:simpleType name="telefonoTipo">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{9}"/>
        </xs:restriction>
     </xs:simpleType>

        <xs:simpleType name="nifTipo">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{8}\-[A-Z]"/>
        </xs:restriction>
     </xs:simpleType>

    <!-- Estructura Matricula-->

    <xs:element name="matricula">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fecha_alta" type="xs:date"/>
                <xs:element name="estado" type="estadoMatricula"/>
            </xs:sequence>
            <!-- Atributos Matricula-->
             <xs:attribute name="id" type="xs:ID" use="required"/>
             <xs:attribute name="alumnoRef" type="xs:IDREF" use="required"/>
             <xs:attribute name="cursoRef" type="xs:IDREF" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Restricciones Matrícula-->
    <xs:simpleType name="estadoMatricula">
        <xs:restriction base="xs:string">
            <xs:pattern value="Pagada|Pendiente"/>
        </xs:restriction>
    </xs:simpleType>


    <!-- Estructura Evaluacion-->
     <xs:element name="evaluacion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="instrumento" type="xs:string"/>
                <xs:element name="convocatoria" type="convocatoriaTipo"/>
                <xs:element name="nota" type="notaTipo"/>
            </xs:sequence>
            <!-- Atributos Evaluación-->
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="matriculaRef" type="xs:IDREF" use="required"/>
        </xs:complexType>
     </xs:element>

    <!-- Restricciones Evaluación-->
     <xs:simpleType name="convocatoriaTipo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Enero"/>
            <xs:enumeration value="Diciembre"/>
            <xs:enumeration value="Junio"/>
            <xs:enumeration value="Julio"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="notaTipo">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== danielmhdev/EV2---Lenguaje-de-Marcas-XML-DTD-XSD/Ejercicio 2/plataforma.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE plataforma SYSTEM "plataforma.dtd">-->


<plataforma fecha_publicacion="2025-10-04" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plataforma.xsd">
    <cursos>
        <curso id="A001" codigo="123456ABC">
            <titulo>Anatomía</titulo>
            <nivel>Basico</nivel>
            <modalidad>Presencial</modalidad>
            <horas>150</horas>
            <modulos>
                <modulo clave ="A01">
                    <nombre>Estructura del Corazón</nombre>
                    <horas>50</horas>
                </modulo>
                 <modulo>
                    <nombre>Sistema esquelético</nombre>
                    <horas>100</horas>
                </modulo>
            </modulos>
        </curso>

        <curso id="A002">
            <titulo>Aparato Digestivo</titulo>
            <nivel>Avanzado</nivel>
            <modalidad>Online</modalidad>
            <horas>60</horas>        
        </curso>
    </cursos>

    <alumnos>
        <alumno id="ABC-012" nif="12345678-A">
            <nombre>Daniel</nombre>
            <email>daniel@gmail.com</email>
            <telefono>667898967</telefono>
        </alumno>

        <alumno id="ABC-013" >
            <nombre>Raul</nombre>
            <email>raul@gmail.com</email>
        </alumno>
    </alumnos>

    <matriculas>
        <matricula id="ABC01" alumnoRef="ABC-012" cursoRef="A002">
            <fecha_alta>2025-10-02</fecha_alta>
            <estado>Pagada</estado>
        </matricula>

        <matricula id="ABC02" alumnoRef="ABC-013" cursoRef="A002">
            <fecha_alta>2025-10-03</fecha_alta>
            <estado>Pendiente</estado>
        </matricula>
    </matriculas>
    
    <evaluaciones>
        <evaluacion id="M001" matriculaRef="ABC01">
            <instrumento>Endoscopio</instrumento>
            <convocatoria>Enero</convocatoria>
            <nota>9.5</nota>
        </evaluacion>

        <evaluacion id="M002" matriculaRef="ABC02">
            <instrumento>Esqueleto humano</instrumento>
            <convocatoria>Julio</convocatoria>
            <nota>8</nota>
        </evaluacion>
    </evaluaciones>
</plataforma>
